name: Test

on: push

jobs:

  build_and_test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Install Volta
        uses: volta-cli/action@v1
        with:
          node-version: '14'
          npm-version: '7'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          npm install
          npm test
